In [1]:
from torch.utils.data import Dataset
from torch.utils.data import Dataloader


ImportError: cannot import name 'Dataloader' from 'torch.utils.data' (c:\Users\vishw\anaconda3_new\envs\cloudremoval\lib\site-packages\torch\utils\data\__init__.py)

In [ ]:
from torch.utils.data import Dataset

class MyDataset(Dataset):
    def __init__(self, data):
        self.data = [10, 20, 30, 40 , 50]
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, index):
        return self.data[index]
    

ImportError: cannot import name 'Dataloader' from 'torch.utils.data' (c:\Users\vishw\anaconda3_new\envs\cloudremoval\lib\site-packages\torch\utils\data\__init__.py)

In [4]:
dataset = MyDataset()

print(dataset[0])
print(dataset[1])
print(dataset[2])



NameError: name 'MyDataset' is not defined

In [ ]:
from torch.utils.data import Dataset 


class MyDataset(Dataset):
    def __init__(self, data): # Note : class ist letter is small c always 
                              # In the name of class ist letter is capital M 
        self.data = data      # __init__ is used to take values and execute automaticallu
                              # when object is created 
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, index):
        return self.data[index]
    

In [ ]:
dataset = MyDataset([1,2,3,4,5])  # Syntax for creating class 
print(dataset[0])                 # dataset = MyDataset() , object = classname()
print(dataset[1])
print(dataset[2])


1
3
5


# from torch.utils.data import Dataset
Why?

Because Dataset is already written by PyTorch engineers.

Inside PyTorch:

torch
 └── utils
      └── data
            └── Dataset

We import it so we can inherit from it.

PyTorch needs a standardized format to talk to your data. It cannot guess how you organized your files on your hard drive.

Here are the primary reasons PyTorch requires this Dataset structure:

Reason A: It Standardizes Data Access
Every machine learning project uses different data types—some use CSV files, some use audio tracks, and others use satellite images.

PyTorch engineers created the Dataset class as a unified interface. No matter what kind of data you are using, PyTorch expects to interact with it using square brackets (dataset[0], dataset[1]). By inheriting from Dataset, you guarantee your custom data structures will seamlessly integrate with the rest of PyTorch's ecosystem.



In [12]:
class Student :

    def __init__(self,name,age):
        self.name = name 
        self.age = age 

    def display(self):
        print(self.name)
        print(self.age)

s1 = Student("RAM" , 21)
s1.display()



RAM
21


In [1]:
from torch.utils.data import Dataset
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data
    def __len__(self):
        return len(self)
    def __get__item(self, index):
        return self.data[index]
    def display(self):
        print(self.data)
dataset = MyDataset([1,2,3,4,5])


print(dataset.display())
print(dataset[0])



    



[1, 2, 3, 4, 5]
None


NotImplementedError: Subclasses of Dataset should implement __getitem__.

In [6]:
from torch.utils.data import Dataset
class MyDataset(Dataset):
    def __init__(self):
        self.data = [1,2,3,4,5]
 

    def __len__(self):
        return len(self.data)

    def __getitem__(self,index):
        return self.data[index]

dataset = MyDataset()

print(len(dataset))


5


In [ ]:
# 1. First, import DataLoader from PyTorch's library
from torch.utils.data import DataLoader

# 2. Now create the DataLoader (This will work perfectly now!)
loader = DataLoader( 
    dataset,
    batch_size = 2,
    shuffle = False # here shuffle is not done but shuffling is done to make
                    # the dataset better like mixed.
)

print("\nBatches:")

# 3. Print the batches
for batch in loader:
    print(batch)


Batches:
tensor([1, 2])
tensor([3, 4])
tensor([5])


In [11]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)
print(type(arr))
print(arr.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [12]:
import torch
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

tensor = torch.tensor(arr)

print(type(arr))
print(type(tensor))

print(arr.shape)
print(tensor.shape)

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
(2, 3)
torch.Size([2, 3])
