In [1]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr)
print(type(arr))
print(arr.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [2]:
import cv2

print(cv2.__version__)

4.13.0


In [ ]:
import numpy as np
import torch
arr = np.array([
    [1,2,3] ,
    [4,5,6]
 ])
tensor = torch.tensor(arr)
print(arr)
print(type(arr))




[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


: 