In [ ]:
import torch # PyTorch is an open-source software library built specifically for artificial intelligence and deep learning
print(torch.__version__)# While standard Python is great for basic tasks, it isn't fast enough to handle the millions of calculations required to process complex data like satellite imagery or video. PyTorch provides the specialized math tools and hardware acceleration needed to train neural networks quickly.
# Torch is used to load pytorch in the notebook. It is a library for tensor computation and deep learning.

2.11.0+cu128


In [ ]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))   # Can PyTorch see my NVIDIA GPU?



True
NVIDIA GeForce RTX 3050 Laptop GPU


In [ ]:
x = torch.tensor([1,2,3])   """ x = torch.tensor([1,2,3]) is a tensor because it takes a standard Python list [1, 2, 3] and wraps it into a PyTorch Tensor object. Specifically, it is a 1-dimensional tensor (a vector) with a shape of torch.Size([3])."""
print(x)
# PyTorch tensors automatically compute the error gradients (loss.backward())  
# to update the model weights. NumPy cannot do this automatically.
# Tensor is a multi-dimensional array that can be used for various mathematical operations, including linear algebra, optimization, and deep learning. Tensors are similar to NumPy arrays but have additional capabilities, such as GPU acceleration and automatic differentiation.
# Tensor is mainly used for parallel computing means the values could be computed in parallel on multiple CPU cores or GPU cores, which can significantly speed up the computation time for large datasets or complex models.
# it automatically computes the gradients and updates the model weights during training, which is essential for deep learning applications. This is done using the autograd feature of PyTorch, which allows for automatic differentiation of tensors.

tensor([1, 2, 3])


In [ ]:
x = torch.tensor([1, 2, 3]) # Tensor is a data building block in pytorch.
print(type(x))  # Tensor it ia mutli-d array that is used for store different types of data 
# Tensor can connect to GPU and CPU for faster computation. It is used for deep learning and machine learning applications .It is similar to NumPy arrays but has additional capabilities, such as GPU acceleration and automatic updates the model weights and fix the error.


<class 'torch.Tensor'>


In [9]:
x = torch.rand(5,3)
print(x)


tensor([[0.7507, 0.0024, 0.8830],
        [0.3201, 0.8816, 0.3804],
        [0.5193, 0.2360, 0.6258],
        [0.5681, 0.2122, 0.0699],
        [0.3809, 0.2618, 0.2055]])


In [ ]:
x = torch.tensor([1,2,3])
print(x.shape)  # Tensor shape is torch.Size([3]) which means it is a 1-dimensional tensor (a vector) with 3 elements. The shape of a tensor is represented as a tuple of integers, where each integer represents the size of the corresponding dimension. In this case, the tensor has only one dimension with a size of 3.
[3] means it is a 1-dimensional tensor (a vector) with 3 elements. The shape of a tensor is represented as a tuple of integers, where each integer represents the size of the corresponding dimension. In this case, the tensor has only one dimension with a size of 3.

torch.Size([3])


In [ ]:
x = torch.tensor( [ [1, 2, 3] ,
                   [4, 5 ,6]
])
print(x)
print(x.shape) # Tensor shape is torch.Size([2, 3]) which means it is a 2-dimensional tensor (a matrix) with 2 rows and 3 columns. The shape of a tensor is represented as a tuple of integers, where each integer represents the size of the corresponding dimension. In this case, the tensor has two dimensions: the first dimension has a size of 2 (indicating the number of rows), and the second dimension has a size of 3 (indicating the number of columns).

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [14]:
device = "cuda"
x_gpu = torch.tensor([1,2,3]).to(device)
print(x_gpu)
print(x_gpu.device)


tensor([1, 2, 3], device='cuda:0')
cuda:0


In [ ]:
# Shifting the tensor to the GPU for blazing-fast speed
x_gpu = x.to('cuda') # Shortest methos to shift a tensor to the gpu is to use the .to() method and specify the device you want to shift it to. In this case, we are shifting the tensor x to the GPU by passing 'cuda' as an argument to the .to() method. This will move the tensor from the CPU memory to the GPU memory, allowing for faster computations when performing operations on the tensor.
print(x_gpu)  

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')
