In [1]:
# Tensors and Images
import torch
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
print(x+y)


tensor([5, 7, 9])


In [2]:
print(x-y)
print(x*y)
print(x/2)


tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.5000, 1.0000, 1.5000])


In [3]:

x = torch.tensor([1,2,3,4,5,6])
print(x.shape)



torch.Size([6])


In [4]:
x =  x.reshape(2,3)
print(x)
print(x.shape)


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [ ]:
import torch
image = torch.rand( 256, 256 , 3)
print(image.shape)

torch.Size([256, 256, 3])


: 